name: maven-publish-central

on:
  workflow_dispatch: # Allows you to trigger the release manually from the UI
      inputs:        
        versionScheme:
          description: 'Version scheme to use'
          required: true
          type: choice
          options:
            - major
            - major-minor
            - major-minor-patch
          default: 'major-minor-patch'

env:
  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: allows the bot to push commits and tags
    
    steps:
      # Checking out the code using GH_ACTION_DEPLOY_KEY allows the bot to push commits
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_ACTION_DEPLOY_KEY }}

      # Not specifying a settings.xml file defaulst to ~/.m2/settings.xml which holds:
      # <servers>
      #   <server>
      #     <id>github</id>
      #     <username>${env.GITHUB_ACTOR}</username>
      #     <password>${env.GITHUB_TOKEN}</password>
      #   </server>
      # </servers>
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'

          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN

          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE


      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      # Computing release version and next snapshot version and saving it to the environment
      - name: Config release versions
        run: |
          curr_version=`./mvnw help:evaluate -Dexpression='project.version' -q -DforceStdout`
          release_version=`./version_sans_qualifier.sh "$curr_version"`
          next_version=`./increment_version.sh "$curr_version"`
          echo "release_version=$release_version" >> $GITHUB_ENV
          echo "next_version=$next_version" >> $GITHUB_ENV
        env:
          VERSION_SCHEME: ${{ github.event.inputs.versionScheme }}

      # Maybe i should move the env vars from the jdk setup here?
      - name: Prepare Release
        run: |
          mvn -B release:prepare \
            -DreleaseVersion=${{ env.release_version }} \
            -DdevelopmentVersion=${{ env.next_version }}

      # mvn release:perform pushes a tag to github with value "v${release_version}"
      - name: Perform Release
        run: |
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
          mvn release:perform
        env:
          JSON_SPLITTER_GITHUB_TOKEN: ${{ github.token }} 
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.JSON_SPLITTER_GITHUB_TOKEN }}

      # Pushing version bump and newly created tags
      - name: Push Changes
        run: |
          git push origin main --tags

      - name: GH release
        run: gh release create "v${VERSION}" --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ secrets.JSON_SPLITTER_GITHUB_TOKEN }}
          VERSION: ${{ env.release_version }}
