name: next-version

on: workflow_dispatch

permissions:
  contents: write

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_ACTION_DEPLOY_KEY }}

      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Augment version
        run: |
          curr_version=`./mvnw help:evaluate -Dexpression='project.version' -q -DforceStdout`
          echo "curr_version = $curr_version"
          next_version=`./increment_version.sh "$curr_version"`
          echo "next_version = $next_version"
          echo "next_version=$next_version" >> $GITHUB_ENV

      - name: Echo version
        run: |
          echo "next_version = ${{ env.next_version }}"
