name: simple-commit

on:
  workflow_dispatch:
    inputs:
      next_version:
        required: true
        type: string
        description: 'Version name'

permissions:
  contents: write

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_ACTION_DEPLOY_KEY }}

      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Silly change
        run: |
          echo `date +"%Y-%m-%d-%H-%M"` >> STUB_FILE.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: STUB_FILE updated"
          git push origin main

      - name: GH release
        run: gh release create "v${VERSION}" --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ secrets.JSON_SPLITTER_GITHUB_TOKEN }}
          VERSION: ${{ inputs.next_version }}
